# config.yml
publish_mode: editorial_workflow
site_url: https://estatewatch.london
logo_url: https://pbs.twimg.com/profile_images/1290966319949582336/jw4u0oX3_400x400.jpg

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'images'
collections:
  - name: 'blog'
    label: 'News Updates'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: 'barkinganddagenham'
    label: 'Barking & Dagenham'
    identifier_field: name
    folder: '_estates/barkinganddagenham/'
    fields:
      - label: "Current Development Status"
        name: "stage"
        widget: "select"
        options:
          - { label: "Proposal Stage", value: "proposal" }
          - { label: "Preparation Stage", value: "preparation" }
          - { label: "Implementation Stage", value: "implementation" }
      - label: 'Name'
        name: 'name'
        widget: 'string'
      - label: 'Borough'
        name: 'borough'
        widget: 'string'
      - label: 'Lat/Long Coordinates'
        name: 'coordinates'
        widget: 'string'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'barnet'
    label: 'Barnet'
    editor:
      preview: false
    identifier_field: name
    folder: '_estates/barnet/'
    fields:
      - label: 'Estate Name'
        name: 'name'
        widget: 'string'
      - label: 'Borough'
        name: 'borough'
        widget: 'string'
      - {label: "Location", name: "location", widget: "map" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Under threat of demolition", value: "underthreat" }
          - { label: "Demolished", value: "demolished" }    
      - label: "Current Development Status"
        name: "stage"
        widget: "select"
        options:
          - { label: "Proposal Stage", value: "Proposal" }
          - { label: "Preparation Stage", value: "Preparation" }
          - { label: "Implementation Stage", value: "Implementation" }
      - label: 'Landlord'
        name: 'landlord'
        widget: 'string'
      - label: 'Developer'
        name: 'developer'
        widget: 'string'
      - label: 'ITLA'
        name: 'itla'
        widget: 'string'
      - label: 'Total Number of Homes'
        name: 'total'
        widget: 'string'
      - label: 'Thumbnail image'
        name: 'thumb'
        widget: 'image' 
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image_path}}'
        field: {label: Image, name: image_path, widget: image}   
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

